[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "yowasp-boolector"
version = "0.1.0"
description = ""
authors = [
    {name = "William D. Jones", email = "thor0505@comcast.net"},
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "ISC"}

dependencies = [
	"importlib_resources; python_version<'3.9'",
	"yowasp-runtime~=1.12",
]

[project.scripts]
yowasp-boolector = "yowasp_boolector:_run_boolector_argv"
